# -*- coding: utf-8 -*-
"""DataMining_Gacorrr Kang b.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1osGStYE6MEiL9drzAnEvcfS47RE4z3UE

# ACTION 2025 — Supervised Pro (No Label Discovery · No GenAI/API · No AutoML)

Patuh aturan. Lakukan fine-tuning supervised dari train_labels.csv, K-Fold + TTA.
"""

import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from PIL import Image
from tqdm.auto import tqdm
import warnings
warnings.filterwarnings('ignore')

import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F # Import F for TTA
from torch.utils.data import Dataset, DataLoader
from torchvision import models, transforms

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans

from google.colab import drive

drive.mount('/content/drive', force_remount=True)

# Random seed
SEED = 42
np.random.seed(SEED)
torch.manual_seed(SEED)
if torch.cuda.is_available():
    torch.cuda.manual_seed(SEED)

# ============================================================================
# SECTION 2.5: DEFINE DATASET CLASS & HELPER FUNCTIONS
# ============================================================================

class FoodDataset(Dataset):
    """Dataset class for food images"""
    def __init__(self, dataframe, transform=None, is_test=False):
        self.df = dataframe.reset_index(drop=True)
        self.transform = transform
        self.is_test = is_test

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        img_path = self.df.iloc[idx]['filepath']

        try:
            image = Image.open(img_path).convert('RGB')
        except Exception as e:
            print(f"❌ Error loading {img_path}: {e}")
            image = Image.new('RGB', (224, 224), color='gray')

        if self.transform:
            image = self.transform(image)

        if self.is_test:
            # For test data
            if 'test_id' in self.df.columns:
                test_id = self.df.iloc[idx]['test_id']
                return image, test_id
            else:
                # Use 'ID' column if 'test_id' is not present (e.g., after renaming for submission)
                 test_id = self.df.iloc[idx]['ID']
                 return image, test_id
        else:
            # For train/val data
            label = self.df.iloc[idx]['label']
            label_idx = config.LABELS.index(label)
            return image, label_idx

def create_model(model_name, num_classes, pretrained=True):
    """Create model function"""
    if model_name == 'resnet50':
        model = models.resnet50(pretrained=pretrained)
        in_features = model.fc.in_features
        model.fc = nn.Linear(in_features, num_classes)
    elif model_name == 'efficientnet_b0':
        model = models.efficientnet_b0(pretrained=pretrained)
        in_features = model.classifier[1].in_features
        model.classifier[1] = nn.Linear(in_features, num_classes)
    elif model_name == 'convnext_tiny':
        model = models.convnext_tiny(pretrained=pretrained)
        # ConvNeXt's classifier is a Sequential with a final Linear layer
        in_features = model.classifier[-1].in_features
        model.classifier[-1] = nn.Linear(in_features, num_classes)
    return model

# Define train_epoch, validate, and extract_features here for completeness
def train_epoch(model, loader, criterion, optimizer, device):
    model.train()
    running_loss = 0.0
    correct = 0
    total = 0

    for images, labels in tqdm(loader, desc='Train'):
        images, labels = images.to(device), labels.to(device)
        optimizer.zero_grad()
        outputs = model(images)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()

        running_loss += loss.item()
        _, predicted = outputs.max(1)
        total += labels.size(0)
        correct += predicted.eq(labels).sum().item()

    return running_loss / len(loader), 100. * correct / total


def quick_train_epoch(model, loader, criterion, optimizer, device):
    model.train()
    running_loss = 0.0
    correct = 0
    total = 0

    for images, labels in tqdm(loader, desc='Quick Train'):
        images, labels = images.to(device), labels.to(device)
        optimizer.zero_grad()
        outputs = model(images)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()

        running_loss += loss.item()
        _, predicted = outputs.max(1)
        total += labels.size(0)
        correct += predicted.eq(labels).sum().item()

    return running_loss / len(loader), 100. * correct / total

def validate(model, loader, criterion, device):
    model.eval()
    running_loss = 0.0
    correct = 0
    total = 0
    all_preds = []
    all_labels = []

    with torch.no_grad():
        for images, labels in tqdm(loader, desc='Val'):
            images, labels = images.to(device), labels.to(device)
            outputs = model(images)
            loss = criterion(outputs, labels)

            running_loss += loss.item()
            _, predicted = outputs.max(1)
            total += labels.size(0)
            correct += predicted.eq(labels).sum().item()

            all_preds.extend(predicted.cpu().numpy())
            all_labels.extend(labels.cpu().numpy())

    return running_loss / len(loader), 100. * correct / total, all_preds, all_labels

def extract_features(model, dataloader, device):
    model.eval()
    features_list = []

    if config.MODEL_NAME == 'resnet50':
        feature_extractor = nn.Sequential(*list(model.children())[:-1])
    elif config.MODEL_NAME == 'efficientnet_b0':
        feature_extractor = nn.Sequential(*list(model.children())[:-1])
    elif config.MODEL_NAME == 'convnext_tiny':
        # For ConvNeXt, 'features' is the feature extraction part
        feature_extractor = model.features

    feature_extractor = feature_extractor.to(device)

    with torch.no_grad():
        for images, _ in tqdm(dataloader, desc='Extracting features'):
            images = images.to(device)
            features = feature_extractor(images)
            features = features.view(features.size(0), -1)
            features_list.append(features.cpu().numpy())

    return np.vstack(features_list)


# ============================================================================
# SECTION 3: CONFIGURATION (LATEST)
# ============================================================================

class Config:
    # Paths - SESUAIKAN DENGAN STRUKTUR FOLDER ANDA
    BASE_PATH = '/content/drive/MyDrive/Colab Notebooks/LOMBA'
    TRAIN_PATH = os.path.join(BASE_PATH, 'train')
    TRAIN_CSV = os.path.join(BASE_PATH, 'seed_label.csv')
    TEST_PATH = os.path.join(BASE_PATH, 'test')
    TEST_CSV = os.path.join(BASE_PATH, 'test.csv')
    OUTPUT_PATH = os.path.join(BASE_PATH, 'output')

    # Label Categories
    LABELS = [
        'Ayam Bakar', 'Ayam Betutu', 'Ayam Goreng', 'Ayam Pop',
        'Bakso', 'Coto Makassar', 'Gado Gado', 'Gudeg',
        'Nasi Goreng', 'Pempek', 'Rawon', 'Rendang',
        'Sate Madura', 'Sate Padang', 'Soto'
    ]

    # Model
    NUM_CLASSES = len(LABELS)
    MODEL_NAME = 'convnext_tiny'  # 'resnet50' atau 'efficientnet_b0' atau 'convnext_tiny'
    IMAGE_SIZE = 448
    BATCH_SIZE = 32

    # Training (sesuai saran Dosen 1)
    EPOCHS = 60  # Banyakin epoch
    # LATEST TUNED HYPERPARAMETERS
    LEARNING_RATE = 1e-4
    WEIGHT_DECAY = 5e-4
    OPTIMIZER = 'adamw'  # 'adamw' atau 'sgd'
    DEVICE = 'cuda' if torch.cuda.is_available() else 'cpu'

    # Augmentation (hati-hati!)
    USE_AUGMENTATION = True
    # LATEST AUGMENTATION LEVEL
    AUGMENTATION_LEVEL = 'moderate'

    # Semi-supervised settings
    USE_SEMI_SUPERVISED = False  # Set False to skip
    # LATEST PSEUDO LABEL THRESHOLD
    PSEUDO_LABEL_THRESHOLD = 0.75 # Increased threshold for higher confidence
    INITIAL_TRAINING_EPOCHS = 20  # Quick training for feature extraction

config = Config()
os.makedirs(config.OUTPUT_PATH, exist_ok=True)
os.makedirs(os.path.join(config.OUTPUT_PATH, 'plots'), exist_ok=True)

print(f"🚀 ACTION 2025 - Consolidated Pipeline (Latest Hyperparameters)")
print(f"Device: {config.DEVICE}")
print(f"Model: {config.MODEL_NAME}")
print(f"Optimizer: {config.OPTIMIZER.upper()}")
print(f"Learning Rate: {config.LEARNING_RATE}")
print(f"Weight Decay: {config.WEIGHT_DECAY}")
print(f"Pseudo Label Threshold: {config.PSEUDO_LABEL_THRESHOLD}")
print(f"Augmentation Level: {config.AUGMENTATION_LEVEL}")
print("="*80)

# Define transforms with latest config values
if config.USE_AUGMENTATION:
    if config.AUGMENTATION_LEVEL == 'light':
        train_transform = transforms.Compose([
            transforms.Resize((config.IMAGE_SIZE, config.IMAGE_SIZE)),
            transforms.RandomHorizontalFlip(p=0.3),
            transforms.RandomRotation(degrees=10),
            transforms.ColorJitter(brightness=0.15, contrast=0.15),
            transforms.ToTensor(),
            transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
        ])
    else: # 'moderate'
        train_transform = transforms.Compose([
            transforms.Resize((config.IMAGE_SIZE, config.IMAGE_SIZE)),
            transforms.RandomHorizontalFlip(p=0.5),
            transforms.RandomRotation(degrees=15),
            transforms.ColorJitter(brightness=0.2, contrast=0.2, saturation=0.1),
            transforms.RandomAffine(degrees=0, translate=(0.1, 0.1)),
            transforms.ToTensor(),
            transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
        ])
else: # No augmentation
    train_transform = transforms.Compose([
        transforms.Resize((config.IMAGE_SIZE, config.IMAGE_SIZE)),
        transforms.ToTensor(),
        transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
    ])

val_transform = transforms.Compose([
    transforms.Resize((config.IMAGE_SIZE, config.IMAGE_SIZE)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])


# ============================================================================
# PHASE 1: DATA LOADING & CLEANING
# ============================================================================

print("\n" + "="*80)
print("PHASE 1: DATA LOADING & CLEANING")
print("="*80)

print(f"\n📂 Loading CSV: {config.TRAIN_CSV}")
df_raw = pd.read_csv(config.TRAIN_CSV)

print(f"✓ Total rows in CSV: {len(df_raw)}")
print(f"✓ Columns: {list(df_raw.columns)}")

# Check column names
if 'filename' not in df_raw.columns:
    possible_names = ['Filename', 'image', 'Image', 'file', 'File', 'img', 'nama_file']
    for col in df_raw.columns:
        if col.lower() in [n.lower() for n in possible_names]:
            df_raw.rename(columns={col: 'filename'}, inplace=True)
            print(f"✓ Renamed column '{col}' → 'filename'")
            break

if 'label' not in df_raw.columns:
    possible_names = ['Label', 'class', 'Class', 'category', 'Category', 'target']
    for col in df_raw.columns:
        if col.lower() in [n.lower() for n in possible_names]:
            df_raw.rename(columns={col: 'label'}, inplace=True)
            print(f"✓ Renamed column '{col}' → 'label'")
            break

# Validate required columns
if 'filename' not in df_raw.columns or 'label' not in df_raw.columns:
    print("\n❌ ERROR: CSV harus memiliki kolom 'filename' dan 'label'")
    raise ValueError("Missing required columns")

print(f"\n📊 Data Overview:")
print(f"├─ Total rows: {len(df_raw)}")
print(f"├─ Rows with label: {df_raw['label'].notna().sum()}")
print(f"├─ Rows without label (NaN): {df_raw['label'].isna().sum()}")
print(f"└─ Unique labels: {df_raw['label'].nunique()}")

# Filter labeled data
print("\n" + "-"*80)
print("STEP 1: Filtering labeled data")
print("-"*80)

train_df = df_raw[df_raw['label'].notna()].copy()
print(f"✓ After removing NaN: {len(train_df)} rows")

train_df = train_df[train_df['label'].astype(str).str.strip() != ''].copy()
print(f"✓ After removing empty strings: {len(train_df)} rows")

valid_labels = set(config.LABELS)
train_df = train_df[train_df['label'].isin(valid_labels)].copy()
print(f"✓ After filtering valid labels: {len(train_df)} rows")

# CRITICAL CHECK: Ensure there are seed labels before proceeding
if len(train_df) == 0:
    raise ValueError("No seed labels found in the specified CSV and matching files in the train directory. Cannot proceed.")


# Fix file paths
print("\n" + "-"*80)
print("STEP 2: Fixing file paths")
print("-"*80)

def find_image_file(filename, search_dir):
    direct_path = os.path.join(search_dir, filename)
    if os.path.exists(direct_path):
        return direct_path

    base_name = os.path.splitext(filename)[0]
    for ext in ['.jpg', '.jpeg', '.png', '.JPG', '.JPEG', '.PNG']:
        test_path = os.path.join(search_dir, base_name + ext)
        if os.path.exists(test_path):
            return test_path

    try:
        all_files = os.listdir(search_dir)
        for f in all_files:
            if f.lower() == filename.lower():
                return os.path.join(search_dir, f)
    except:
        pass

    return None

valid_rows = []
missing_files = []

print(f"Searching for files in: {config.TRAIN_PATH}")
for idx, row in tqdm(train_df.iterrows(), total=len(train_df)):
    filename = row['filename']
    filepath = find_image_file(filename, config.TRAIN_PATH)

    if filepath is not None:
        valid_rows.append({
            'filename': filename,
            'filepath': filepath,
            'label': row['label']
        })
    else:
        missing_files.append(filename)

train_df = pd.DataFrame(valid_rows)

print(f"\n✓ Files found: {len(train_df)}")
print(f"✗ Files missing: {len(missing_files)}")

if len(train_df) == 0:
    raise ValueError("No image files found!")

# Display statistics
print("\n" + "-"*80)
print("STEP 3: Final Data Statistics")
print("-"*80)

print(f"\n✅ Successfully loaded {len(train_df)} labeled images")

label_counts = train_df['label'].value_counts().sort_index()
print("\n📊 Original Labeled Data Distribution:")
display(label_counts)

# train_df.to_csv(os.path.join(config.OUTPUT_PATH, 'train_cleaned.csv'), index=False)
# print(f"\n💾 Cleaned data saved: train_cleaned.csv")


# ============================================================================
# PHASE 1.5: SEMI-SUPERVISED LABELING
# ============================================================================

if config.USE_SEMI_SUPERVISED:
    print("\n" + "="*80)
    print("PHASE 1.5: SEMI-SUPERVISED LABELING")
    print("="*80)

    # Load ALL train images
    print("\n📂 Loading all train images...")
    all_train_files = []
    for root, dirs, files in os.walk(config.TRAIN_PATH):
        for file in files:
            if file.lower().endswith(('.jpg', '.jpeg', '.png')):
                full_path = os.path.join(root, file)
                all_train_files.append({
                    'filename': file,
                    'filepath': full_path
                })

    print(f"✓ Found {len(all_train_files)} total train images")

    # Separate labeled vs unlabeled
    labeled_files = set(train_df['filepath'].tolist()) # Use the train_df from Phase 1
    unlabeled_files = [f for f in all_train_files if f['filepath'] not in labeled_files]

    print(f"✓ Labeled: {len(labeled_files)}")
    print(f"✓ Unlabeled: {len(unlabeled_files)}")

    if len(unlabeled_files) > 50:  # Only do semi-supervised if significant unlabeled data
        print(f"\n🔬 Starting semi-supervised labeling on {len(unlabeled_files)} images...")

        # STEP 1: Quick initial training for feature extraction
        # Reuse quick_train_epoch, validate, create_model, extract_features functions
        print("\n" + "-"*80)
        print("STEP 1: Initial Model Training (for feature extraction)")
        print("-"*80)

        # Train-val split - Use the labeled data from Phase 1 for this initial training
        initial_train_data, initial_val_data = train_test_split(
            train_df,
            test_size=0.2,
            stratify=train_df['label'],
            random_state=SEED
        )

        initial_train_dataset = FoodDataset(initial_train_data, transform=train_transform)
        initial_val_dataset = FoodDataset(initial_val_data, transform=val_transform)

        # Modified num_workers to 0 to avoid multiprocessing errors
        initial_train_loader = DataLoader(initial_train_dataset, batch_size=config.BATCH_SIZE,
                                         shuffle=True, num_workers=0, pin_memory=True)
        # Modified num_workers to 0 to avoid multiprocessing errors
        initial_val_loader = DataLoader(initial_val_dataset, batch_size=config.BATCH_SIZE,
                                       shuffle=False, num_workers=0, pin_memory=True)

        # Create initial model
        initial_model = create_model(config.MODEL_NAME, config.NUM_CLASSES, True).to(config.DEVICE)
        print(f"✓ Initial model created: {config.MODEL_NAME}")

        criterion = nn.CrossEntropyLoss()
        # Use a slightly higher LR and lower WD for the initial training to converge faster
        initial_optimizer = optim.AdamW(initial_model.parameters(), lr=1e-4,
                               weight_decay=1e-3)


        print(f"\n🚀 Quick initial training ({config.INITIAL_TRAINING_EPOCHS} epochs)...")
        for epoch in range(config.INITIAL_TRAINING_EPOCHS):
            train_loss, train_acc = quick_train_epoch(initial_model, initial_train_loader,
                                                      criterion, initial_optimizer, config.DEVICE)
            if (epoch + 1) % 5 == 0:
                print(f"Epoch {epoch+1}/{config.INITIAL_TRAINING_EPOCHS}: "
                      f"Loss={train_loss:.4f}, Acc={train_acc:.2f}%")

        print("✓ Initial training complete")

        # STEP 2: Feature Extraction
        print("\n" + "-"*80)
        print("STEP 2: Feature Extraction")
        print("-"*80)

        # Extract from labeled data (from Phase 1)
        print("Extracting features from labeled data...")
        labeled_dataset_feat = FoodDataset(train_df, transform=val_transform, is_test=False)
        # Modified num_workers to 0 to avoid multiprocessing errors
        labeled_loader_feat = DataLoader(labeled_dataset_feat, batch_size=32,
                                        shuffle=False, num_workers=0)

        labeled_features = extract_features(initial_model, labeled_loader_feat, config.DEVICE)
        labeled_labels = train_df['label'].apply(lambda x: config.LABELS.index(x)).values

        print(f"✓ Labeled features shape: {labeled_features.shape}")

        # Extract from unlabeled data
        print("Extracting features from unlabeled data...")
        unlabeled_df = pd.DataFrame(unlabeled_files)
        unlabeled_df['label'] = config.LABELS[0]  # Temporary label

        unlabeled_dataset = FoodDataset(unlabeled_df, transform=val_transform, is_test=False)
        # Modified num_workers to 0 to avoid multiprocessing errors
        unlabeled_loader = DataLoader(unlabeled_dataset, batch_size=32,
                                     shuffle=False, num_workers=0)

        unlabeled_features = extract_features(initial_model, unlabeled_loader, config.DEVICE)
        print(f"✓ Unlabeled features shape: {unlabeled_features.shape}")

        # STEP 3: PCA
        # Reuse PCA
        print("\n" + "-"*80)
        print("STEP 3: PCA Dimensionality Reduction")
        print("-"*80)

        n_components = min(256, labeled_features.shape[0], labeled_features.shape[1])
        pca = PCA(n_components=n_components, random_state=SEED)

        pca.fit(labeled_features)
        variance_explained = np.sum(pca.explained_variance_ratio_)
        print(f"✓ PCA components: {n_components}")
        print(f"✓ Variance explained: {variance_explained:.3f}")

        labeled_features_pca = pca.transform(labeled_features)
        unlabeled_features_pca = pca.transform(unlabeled_features)

        # STEP 4: K-Means Clustering
        # Reuse KMeans
        print("\n" + "-"*80)
        print("STEP 4: K-Means Clustering")
        print("-"*80)

        # Initialize centroids from labeled data
        initial_centroids = []
        for label_idx in range(config.NUM_CLASSES):
            class_features = labeled_features_pca[labeled_labels == label_idx]
            if len(class_features) > 0:
                centroid = class_features.mean(axis=0)
                initial_centroids.append(centroid)
            else:
                # Handle classes with no labeled samples by taking a random unlabeled sample's feature
                if len(unlabeled_features_pca) > 0:
                     random_idx = np.random.choice(len(unlabeled_features_pca))
                     initial_centroids.append(unlabeled_features_pca[random_idx])
                else:
                     # Fallback if no labeled or unlabeled data
                     initial_centroids.append(np.zeros(n_components)) # Use a zero vector


        # Ensure we have enough centroids for all clusters
        while len(initial_centroids) < config.NUM_CLASSES:
             if len(unlabeled_features_pca) > 0:
                random_idx = np.random.choice(len(unlabeled_features_pca))
                initial_centroids.append(unlabeled_features_pca[random_idx])
             else:
                initial_centroids.append(np.zeros(n_components)) # Use a zero vector

        initial_centroids = np.array(initial_centroids)
        # Ensure init has correct shape [n_clusters, n_features]
        if initial_centroids.shape[0] != config.NUM_CLASSES or initial_centroids.shape[1] != n_components:
             print("Warning: Initial centroids shape mismatch. Recalculating or using random init.")
             # Fallback to k-means++ if custom init fails
             kmeans = KMeans(n_clusters=config.NUM_CLASSES,
                       init='k-means++', # Fallback to k-means++
                       n_init=10, # Use default n_init for robustness
                       random_state=SEED,
                       max_iter=300)
        else:
            kmeans = KMeans(n_clusters=config.NUM_CLASSES,
                       init=initial_centroids,
                       n_init=1, # Explicitly set n_init=1 when using custom init
                       random_state=SEED,
                       max_iter=300)


        unlabeled_clusters = kmeans.fit_predict(unlabeled_features_pca)

        # Calculate confidence
        distances = kmeans.transform(unlabeled_features_pca)
        min_distances = distances.min(axis=1)
        max_distances = distances.max(axis=1)
        # Avoid division by zero if max_distances is 0 (all points are the same)
        confidence_scores = 1 - (min_distances / (max_distances + 1e-8))


        print(f"✓ Clustering complete")
        print(f"✓ Confidence: min={confidence_scores.min():.3f}, "
              f"max={confidence_scores.max():.3f}, mean={confidence_scores.mean():.3f}")

        # STEP 5: Select pseudo-labels
        print("\n" + "-"*80)
        print("STEP 5: Selecting High-Confidence Pseudo-Labels")
        print("-"*80)

        high_confidence_mask = confidence_scores >= config.PSEUDO_LABEL_THRESHOLD # Use updated threshold

        print(f"✓ Threshold: {config.PSEUDO_LABEL_THRESHOLD}")
        print(f"✓ High-confidence samples: {high_confidence_mask.sum()} / {len(unlabeled_df)}")

        if high_confidence_mask.sum() > 0:
            pseudo_labeled_data = []

            for idx in range(len(unlabeled_df)):
                if high_confidence_mask[idx]:
                    cluster = unlabeled_clusters[idx]
                    pseudo_label = config.LABELS[cluster]
                    confidence = confidence_scores[idx]

                    pseudo_labeled_data.append({
                        'filename': unlabeled_df.iloc[idx]['filename'],
                        'filepath': unlabeled_df.iloc[idx]['filepath'],
                        'label': pseudo_label,
                        'confidence': confidence,
                        'is_pseudo': True
                    })

            pseudo_df = pd.DataFrame(pseudo_labeled_data)

            print(f"\n📊 Pseudo-label distribution:")
            pseudo_label_counts = pseudo_df['label'].value_counts().sort_index()
            display(pseudo_label_counts)

            # Combine (Overwrite train_df with combined data)
            train_df['is_pseudo'] = False
            train_df['confidence'] = 1.0

            train_df = pd.concat([train_df, pseudo_df], ignore_index=True)

            print(f"\n✅ Enhanced training set:")
            print(f"├─ Original labeled: {len(labeled_files)}")
            print(f"├─ Pseudo-labeled: {len(pseudo_df)}")
            print(f"└─ Total: {len(train_df)}")

            pseudo_df.to_csv(os.path.join(config.OUTPUT_PATH, 'pseudo_labels.csv'), index=False)
            print(f"💾 Saved: pseudo_labels.csv")
        else:
            print("⚠️ No high-confidence pseudo-labels found with the current threshold.")
            print("Proceeding with original labeled data only.")
            train_df['is_pseudo'] = False
            train_df['confidence'] = 1.0 # Ensure columns match even if no pseudo-labels added

    else:
        print("\n⚠️ Semi-supervised learning disabled in config. Proceeding with original labeled data only.")
        train_df['is_pseudo'] = False
        train_df['confidence'] = 1.0 # Ensure columns match if disabled


# ============================================================================
# PHASE 2: DATA PREPARATION
# ============================================================================

print("\n" + "="*80)
print("PHASE 2: DATA PREPARATION")
print("="*80)

# Train-val split - Use the potentially updated train_df
train_data, val_data = train_test_split(
    train_df,
    test_size=0.2,
    stratify=train_df['label'],
    random_state=SEED
)

print(f"✓ Train: {len(train_data)} images")
print(f"✓ Val: {len(val_data)} images")

# Datasets & loaders
# Reuse FoodDataset, train_transform, val_transform
train_dataset = FoodDataset(train_data, transform=train_transform)
val_dataset = FoodDataset(val_data, transform=val_transform)

# Modified num_workers to 0 to avoid multiprocessing errors
train_loader = DataLoader(train_dataset, batch_size=config.BATCH_SIZE,
                         shuffle=True, num_workers=0, pin_memory=True)
# Modified num_workers to 0 to avoid multiprocessing errors
val_loader = DataLoader(val_dataset, batch_size=config.BATCH_SIZE,
                       shuffle=False, num_workers=0, pin_memory=True)

print(f"✓ Train batches: {len(train_loader)}")
print(f"✓ Val batches: {len(val_loader)}")


# ============================================================================
# PHASE 3: MODEL SETUP & TRAINING
# ============================================================================

print("\n" + "="*80)
print("PHASE 3: MODEL SETUP & TRAINING")
print("="*80)

# Reuse create_model function
model = create_model(config.MODEL_NAME, config.NUM_CLASSES, True).to(config.DEVICE)
print(f"\n✓ Model: {config.MODEL_NAME}")
print(f"✓ Parameters: {sum(p.numel() for p in model.parameters()):,}")

criterion = nn.CrossEntropyLoss()

if config.OPTIMIZER == 'adamw':
    optimizer = optim.AdamW(model.parameters(), lr=config.LEARNING_RATE, # Use updated LR
                           weight_decay=config.WEIGHT_DECAY) # Use updated WD
elif config.OPTIMIZER == 'sgd':
    optimizer = optim.SGD(model.parameters(), lr=config.LEARNING_RATE, # Use updated LR
                         momentum=0.9, weight_decay=config.WEIGHT_DECAY) # Use updated WD
else: # Fallback to AdamW if optimizer is not recognized
    print("\n⚠️ Warning: Optimizer not recognized. Falling back to AdamW.")
    optimizer = optim.AdamW(model.parameters(), lr=config.LEARNING_RATE,
                           weight_decay=config.WEIGHT_DECAY)

scheduler = optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode='max',
                                                  factor=0.5, patience=4) # Patience for scheduler can remain 4

# Training
history = {'train_loss': [], 'train_acc': [], 'val_loss': [], 'val_acc': []}
best_val_acc = 0.0
patience_counter = 0
early_stop_patience = 15 # Use updated early stop patience

print("\n🚀 Starting Training...")
print(f"Target: Train 85-95%, Val 75-85%")
print("="*80)

for epoch in range(config.EPOCHS):
    print(f"\nEpoch {epoch+1}/{config.EPOCHS}")
    print("-" * 50)

    train_loss, train_acc = train_epoch(model, train_loader, criterion, optimizer, config.DEVICE)
    val_loss, val_acc, val_preds, val_labels = validate(model, val_loader, criterion, config.DEVICE)

    history['train_loss'].append(train_loss)
    history['train_acc'].append(train_acc)
    history['val_loss'].append(val_loss)
    history['val_acc'].append(val_acc)

    print(f"Train: Loss={train_loss:.4f}, Acc={train_acc:.2f}%")
    print(f"Val:   Loss={val_loss:.4f}, Acc={val_acc:.2f}%")

    # Adjusted overfitting detection threshold
    if train_acc - val_acc > 12: # Slightly reduced threshold
        print("⚠️ Overfitting detected!")

    scheduler.step(val_acc)

    if val_acc > best_val_acc:
        best_val_acc = val_acc
        torch.save({
            'epoch': epoch,
            'model_state_dict': model.state_dict(),
            'optimizer_state_dict': optimizer.state_dict(),
            'val_acc': val_acc,
            'train_acc': train_acc,
        }, os.path.join(config.OUTPUT_PATH, 'best_model.pth'))
        print(f"✅ Best model saved! Val Acc: {val_acc:.2f}%")
        patience_counter = 0
    else:
        patience_counter += 1

    if patience_counter >= early_stop_patience:
        print(f"\n🛑 Early stopping at epoch {epoch+1}")
        break

print(f"\n✅ Training complete! Best Val Acc: {best_val_acc:.2f}%")

# Plot & evaluation
fig, axes = plt.subplots(1, 2, figsize=(15, 5))
axes[0].plot(history['train_loss'], label='Train', marker='o')
axes[0].plot(history['val_loss'], label='Val', marker='s')
axes[0].set_xlabel('Epoch')
axes[0].set_ylabel('Loss')
axes[0].set_title('Loss Curve')
axes[0].legend()
axes[0].grid(True, alpha=0.3)

axes[1].plot(history['train_acc'], label='Train', marker='o')
axes[1].plot(history['val_acc'], label='Val', marker='s')
axes[1].set_xlabel('Epoch')
axes[1].set_ylabel('Accuracy (%)')
axes[1].set_title('Accuracy Curve')
axes[1].legend()
axes[1].grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig(os.path.join(config.OUTPUT_PATH, 'plots', 'training_history.png'), dpi=300)
plt.show()

# Load best model & evaluate
checkpoint = torch.load(os.path.join(config.OUTPUT_PATH, 'best_model.pth'))
model.load_state_dict(checkpoint['model_state_dict'])
model.to(config.DEVICE) # Ensure model is on the correct device
val_loss, val_acc, val_preds, val_labels = validate(model, val_loader, criterion, config.DEVICE)

print("\n📊 Validation Performance:")
print(classification_report(val_labels, val_preds, target_names=config.LABELS, digits=4))

cm = confusion_matrix(val_labels, val_preds)
plt.figure(figsize=(14, 12))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=config.LABELS, yticklabels=config.LABELS)
plt.title('Confusion Matrix')
plt.xlabel('Predicted')
plt.ylabel('True')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.savefig(os.path.join(config.OUTPUT_PATH, 'plots', 'confusion_matrix.png'), dpi=300)
plt.show()

# ============================================================================
# ENHANCEMENT: TEST-TIME AUGMENTATION (TTA)
# ============================================================================

# Add this function before Phase 4 (Test Prediction)

def predict_with_tta(model, image, device, num_augments=5):
    """
    Test-Time Augmentation: Predict on multiple augmented versions
    and average the predictions
    """
    model.eval()

    # Original prediction
    with torch.no_grad():
        image_batch = image.unsqueeze(0).to(device)
        output = model(image_batch)
        predictions = [F.softmax(output, dim=1).cpu()]

    # Augmented predictions
    tta_transforms = [
        transforms.Compose([
            transforms.ToPILImage(),
            transforms.RandomHorizontalFlip(p=1.0),
            transforms.ToTensor(),
            transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
        ]),
        transforms.Compose([
            transforms.ToPILImage(),
            transforms.RandomRotation(degrees=5),
            transforms.ToTensor(),
            transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
        ]),
        transforms.Compose([
            transforms.ToPILImage(),
            transforms.ColorJitter(brightness=0.1),
            transforms.ToTensor(),
            transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
        ]),
    ]

    # Convert tensor back to PIL for augmentation
    image_pil = transforms.ToPILImage()(image)

    for transform in tta_transforms[:num_augments-1]:
        aug_image = transform(image_pil).unsqueeze(0).to(device)
        with torch.no_grad():
            output = model(aug_image)
            predictions.append(F.softmax(output, dim=1).cpu())

    # Average predictions
    avg_prediction = torch.stack(predictions).mean(dim=0)
    _, predicted_class = avg_prediction.max(1)

    return predicted_class.item(), avg_prediction.squeeze()

# Usage in Phase 4 - replace the prediction loop with:
# ============================================================================
# DIAGNOSTIC: Check test.csv structure
# ============================================================================

print("="*80)
print("DIAGNOSTIC: Checking test.csv")
print("="*80)

test_check = pd.read_csv(config.TEST_CSV)

print(f"\nTotal rows: {len(test_check)}")
print(f"Columns: {list(test_check.columns)}")

if 'label' in test_check.columns:
    print(f"\nRows WITH labels: {test_check['label'].notna().sum()}")
    print(f"Rows WITHOUT labels (NaN/empty): {test_check['label'].isna().sum()}")

    # Show first 10 rows
    print("\nFirst 10 rows:")
    print(test_check.head(10))

    # Show rows 995-1005 (around the transition)
    print("\nRows 995-1005 (around transition):")
    print(test_check.iloc[995:1005] if len(test_check) > 1005 else test_check.tail(10))

    # Show last 10 rows
    print("\nLast 10 rows:")
    print(test_check.tail(10))

    # Check where NaN starts
    first_nan_idx = test_check[test_check['label'].isna()].index[0] if test_check['label'].isna().any() else None
    if first_nan_idx:
        print(f"\n⚠️ Labels become NaN starting from row index: {first_nan_idx}")
        print(f"Row {first_nan_idx} details:")
        print(test_check.iloc[first_nan_idx])
else:
    print("\nNo 'label' column found (this is normal for test sets)")
    print("\nFirst 10 rows:")
    print(test_check.head(10))
    print("\nLast 10 rows:")
    print(test_check.tail(10))

if 'ID' in test_check.columns:
    print(f"\nID range: {test_check['ID'].min()} to {test_check['ID'].max()}")
    print(f"ID type: {test_check['ID'].dtype}")

print("\n" + "="*80)

# ============================================================================
# DIAGNOSTIC PHASE: CHECK TEST DATA STRUCTURE
# ============================================================================
print("\n" + "="*80)
print("DIAGNOSTIC: ANALYZING TEST FOLDER STRUCTURE")
print("="*80)

# First, let's see what's actually in the test folder
print(f"\n🔍 Checking test folder: {config.TEST_PATH}")
print(f"Folder exists: {os.path.exists(config.TEST_PATH)}")

if os.path.exists(config.TEST_PATH):
    # Get all files
    all_test_files = []
    for root, dirs, files in os.walk(config.TEST_PATH):
        for file in files:
            if file.lower().endswith(('.jpg', '.jpeg', '.png')):
                full_path = os.path.join(root, file)
                rel_path = os.path.relpath(full_path, config.TEST_PATH)
                all_test_files.append({
                    'filename': file,
                    'full_path': full_path,
                    'relative_path': rel_path
                })

    print(f"\n✓ Found {len(all_test_files)} image files in test folder")

    # Show samples
    print(f"\n📋 First 15 files:")
    for f in all_test_files[:15]:
        print(f"  - {f['filename']} → {f['relative_path']}")

    print(f"\n📋 Last 15 files:")
    for f in all_test_files[-15:]:
        print(f"  - {f['filename']} → {f['relative_path']}")

    # Analyze naming pattern
    filenames = [f['filename'] for f in all_test_files]

    # Extract numeric IDs from filenames
    numeric_ids = []
    for fname in filenames:
        basename = os.path.splitext(fname)[0]
        if basename.isdigit():
            numeric_ids.append(int(basename))

    if numeric_ids:
        numeric_ids_sorted = sorted(numeric_ids)
        print(f"\n📊 Numeric ID Analysis:")
        print(f"├─ Total files with numeric names: {len(numeric_ids)}")
        print(f"├─ ID range: {min(numeric_ids)} to {max(numeric_ids)}")
        print(f"├─ First 10 IDs: {numeric_ids_sorted[:10]}")
        print(f"└─ Last 10 IDs: {numeric_ids_sorted[-10:]}")

        # Check for gaps
        expected_ids = set(range(min(numeric_ids), max(numeric_ids) + 1))
        actual_ids = set(numeric_ids)
        missing_ids = expected_ids - actual_ids

        if missing_ids:
            missing_sorted = sorted(missing_ids)
            print(f"\n⚠️ Missing IDs detected: {len(missing_ids)} gaps")
            print(f"First 20 missing: {missing_sorted[:20]}")
else:
    print(f"❌ Test folder not found!")
    all_test_files = []

# ============================================================================
# LOAD TEST.CSV AND ANALYZE
# ============================================================================
print("\n" + "="*80)
print("ANALYZING TEST.CSV STRUCTURE")
print("="*80)

print(f"\n📂 Loading: {config.TEST_CSV}")
test_csv_df = pd.read_csv(config.TEST_CSV)

print(f"✓ Loaded {len(test_csv_df)} rows")
print(f"✓ Columns: {list(test_csv_df.columns)}")

print(f"\n📋 First 10 rows:")
print(test_csv_df.head(10))

print(f"\n📋 Rows 995-1005:")
if len(test_csv_df) > 1005:
    print(test_csv_df.iloc[995:1005])

print(f"\n📋 Last 10 rows:")
print(test_csv_df.tail(10))

# Detect ID column
id_column = None
if 'ID' in test_csv_df.columns:
    id_column = 'ID'
elif 'id' in test_csv_df.columns:
    id_column = 'id'
elif 'filename' in test_csv_df.columns:
    id_column = 'filename'
else:
    id_column = test_csv_df.columns[0]

print(f"\n✓ Using '{id_column}' as ID column")
print(f"✓ ID dtype: {test_csv_df[id_column].dtype}")
print(f"✓ ID range: {test_csv_df[id_column].min()} to {test_csv_df[id_column].max()}")

# ============================================================================
# PHASE 4: INTELLIGENT FILE MATCHING
# ============================================================================
print("\n" + "="*80)
print("PHASE 4: TEST PREDICTION - INTELLIGENT FILE MATCHING")
print("="*80)

# Create a lookup dictionary for fast file matching
file_lookup = {}
for f in all_test_files:
    # Create multiple keys for each file
    basename = os.path.splitext(f['filename'])[0]

    # Key 1: exact filename
    file_lookup[f['filename'].lower()] = f['full_path']

    # Key 2: basename without extension
    file_lookup[basename.lower()] = f['full_path']

    # Key 3: if numeric, use as integer key
    if basename.isdigit():
        file_lookup[int(basename)] = f['full_path']
        file_lookup[str(int(basename))] = f['full_path']  # Also as string

print(f"\n✓ Created lookup table with {len(file_lookup)} keys")
print(f"Sample keys: {list(file_lookup.keys())[:20]}")

# Match CSV rows to files
print(f"\n🔍 Matching {len(test_csv_df)} CSV rows to files...")

matched_rows = []
unmatched_rows = []

for idx, row in tqdm(test_csv_df.iterrows(), total=len(test_csv_df), desc="Matching"):
    test_id = row[id_column]
    matched = False
    filepath = None

    # Strategy 1: Try as-is
    if test_id in file_lookup:
        filepath = file_lookup[test_id]
        matched = True

    # Strategy 2: Try with .jpg extension
    if not matched:
        search_key = f"{test_id}.jpg".lower()
        if search_key in file_lookup:
            filepath = file_lookup[search_key]
            matched = True

    # Strategy 3: Try as string
    if not matched:
        search_key = str(test_id).lower()
        if search_key in file_lookup:
            filepath = file_lookup[search_key]
            matched = True

    # Strategy 4: Try as integer (if possible)
    if not matched:
        try:
            search_key = int(test_id)
            if search_key in file_lookup:
                filepath = file_lookup[search_key]
                matched = True
        except:
            pass

    # Strategy 5: Direct file search as last resort
    if not matched:
        possible_names = [
            f"{test_id}.jpg",
            f"{test_id}.jpeg",
            f"{test_id}.png",
            f"{test_id}.JPG",
            f"{test_id}.JPEG",
            f"{test_id}.PNG",
        ]
        for name in possible_names:
            test_path = os.path.join(config.TEST_PATH, name)
            if os.path.exists(test_path):
                filepath = test_path
                matched = True
                break

    if matched and filepath:
        matched_rows.append({
            'test_id': test_id,
            'filepath': filepath
        })
    else:
        unmatched_rows.append({
            'test_id': test_id,
            'row_idx': idx
        })

print(f"\n📊 Matching Results:")
print(f"✓ Matched: {len(matched_rows)} / {len(test_csv_df)}")
print(f"✗ Unmatched: {len(unmatched_rows)}")

# CRITICAL CHECK
if len(matched_rows) == 0:
    print("\n❌ CRITICAL ERROR: NO FILES MATCHED!")
    print("\n🔧 Debugging Info:")
    print(f"CSV ID samples: {test_csv_df[id_column].head(10).tolist()}")
    print(f"Lookup keys sample: {list(file_lookup.keys())[:20]}")
    raise ValueError("No files could be matched. Check file naming convention!")

if len(unmatched_rows) > 0:
    print(f"\n⚠️ WARNING: {len(unmatched_rows)} files could not be matched!")
    print(f"\nFirst 20 unmatched:")
    for um in unmatched_rows[:20]:
        print(f"  Row {um['row_idx']}: ID = {um['test_id']}")

    print(f"\n🔍 Possible causes:")
    print("1. Files don't exist in test folder")
    print("2. Naming convention mismatch")
    print("3. Files in subdirectories")

    # Show what we're looking for vs what exists
    print(f"\nWe're looking for IDs like: {test_csv_df[id_column].head(5).tolist()}")
    print(f"Files in folder look like: {[f['filename'] for f in all_test_files[:5]]}")

# Create test dataframe with matched files only
test_df = pd.DataFrame(matched_rows)

if len(test_df) == 0:
    raise ValueError("No test files could be matched!")

print(f"\n✓ Proceeding with {len(test_df)} matched files")

# ============================================================================
# GENERATE PREDICTIONS
# ============================================================================
print(f"\n🔮 Generating predictions for {len(test_df)} images...")

# Create dataset
test_dataset = FoodDataset(test_df, transform=val_transform, is_test=True)
test_loader = DataLoader(test_dataset, batch_size=config.BATCH_SIZE,
                         shuffle=False, num_workers=2, pin_memory=True)

# Predict
model.eval()
predictions_map = {}  # test_id -> predicted_label

with torch.no_grad():
    for batch_idx, (images, paths) in enumerate(tqdm(test_loader, desc='Predicting')):
        images = images.to(config.DEVICE)
        outputs = model(images)
        _, predicted = outputs.max(1)

        # Get predictions
        batch_preds = [config.LABELS[idx] for idx in predicted.cpu().numpy()]

        # Get corresponding test IDs
        start_idx = batch_idx * config.BATCH_SIZE
        end_idx = start_idx + len(batch_preds)
        batch_ids = test_df.iloc[start_idx:end_idx]['test_id'].tolist()

        # Map ID to prediction
        for tid, pred in zip(batch_ids, batch_preds):
            predictions_map[tid] = pred

print(f"\n✓ Generated {len(predictions_map)} predictions")

# ============================================================================
# CREATE SUBMISSION FILE
# ============================================================================
print(f"\n📝 Creating submission file...")

# Build submission matching the EXACT order and format of test.csv
submission_data = []

for idx, row in test_csv_df.iterrows():
    test_id = row[id_column]

    # Get prediction if available
    if test_id in predictions_map:
        pred_label = predictions_map[test_id]
    else:
        # File was not matched - this should NOT happen ideally
        # But if it does, we need a prediction
        print(f"⚠️ Warning: No prediction for ID {test_id} (row {idx})")
        pred_label = "Nasi Goreng"  # Default fallback (most common Indonesian food)

    submission_data.append({
        'ID': test_id,
        'label': pred_label
    })

submission_df = pd.DataFrame(submission_data)

# VERIFICATION
print(f"\n✅ Submission File Verification:")
print(f"├─ Total rows: {len(submission_df)}")
print(f"├─ Expected rows: {len(test_csv_df)}")
print(f"├─ Match: {'✓ YES' if len(submission_df) == len(test_csv_df) else '✗ NO MISMATCH!'}")
print(f"└─ Columns: {list(submission_df.columns)}")

# Check ID coverage
print(f"\n📊 ID Coverage:")
print(f"├─ CSV IDs: {test_csv_df[id_column].min()} to {test_csv_df[id_column].max()}")
print(f"├─ Submission IDs: {submission_df['ID'].min()} to {submission_df['ID'].max()}")
print(f"└─ All IDs present: {set(test_csv_df[id_column]) == set(submission_df['ID'])}")

# Save
submission_path = os.path.join(config.OUTPUT_PATH, 'submission.csv')
submission_df.to_csv(submission_path, index=False)

print(f"\n💾 Saved: {submission_path}")

# Show prediction distribution
print("\n📊 Prediction Distribution:")
pred_dist = submission_df['label'].value_counts().sort_index()
print(pred_dist)

# Show samples
print("\n🔍 Submission Preview:")
print("\nFirst 10 rows:")
print(submission_df.head(10).to_string(index=False))

print("\nRows 995-1005:")
if len(submission_df) > 1005:
    print(submission_df.iloc[995:1005].to_string(index=False))
else:
    print("(Less than 1005 rows total)")

print("\nLast 10 rows:")
print(submission_df.tail(10).to_string(index=False))

# Visualize
plt.figure(figsize=(14, 6))
pred_dist.plot(kind='bar', color='coral', edgecolor='black')
plt.title(f'Test Predictions Distribution (n={len(submission_df)})',
          fontsize=16, fontweight='bold')
plt.xlabel('Food Category', fontsize=13)
plt.ylabel('Count', fontsize=13)
plt.xticks(rotation=45, ha='right', fontsize=11)
plt.grid(axis='y', alpha=0.3)
plt.tight_layout()
plt.savefig(os.path.join(config.OUTPUT_PATH, 'plots', 'test_predictions.png'), dpi=300)
plt.show()

print("\n" + "="*80)
print("🎉 TEST PREDICTION COMPLETE!")
print("="*80)
print(f"\n📊 Summary:")
print(f"├─ Total test images: {len(test_csv_df)}")
print(f"├─ Successfully matched: {len(matched_rows)}")
print(f"├─ Predictions generated: {len(predictions_map)}")
print(f"└─ Submission rows: {len(submission_df)}")

if len(unmatched_rows) > 0:
    print(f"\n⚠️ WARNING: {len(unmatched_rows)} files were not found!")
    print("These used fallback predictions. Check your test folder structure.")
else:
    print(f"\n✅ All files successfully matched and predicted!")

print("\n✅ Ready to submit!")
print("="*80)

# ============================================================================
# SUMMARY
# ============================================================================

print("\n" + "="*80)
print("🎉 PIPELINE COMPLETE!")
print("="*80)

print("\n📊 Final Results:")
print(f"├─ Training Accuracy:   {history['train_acc'][-1]:.2f}%")
print(f"├─ Validation Accuracy: {best_val_acc:.2f}%")
print(f"├─ Total Epochs:        {len(history['train_acc'])}")
print(f"└─ Best Epoch:          {checkpoint['epoch']+1}")

print("\n📁 Output Files:")
print(f"├─ best_model.pth           ✓")
print(f"├─ submission.csv           ✓")
print(f"└─ plots/")
print(f"    ├─ label_distribution.png")
print(f"    ├─ training_history.png")
print(f"    ├─ confusion_matrix.png")
print(f"    └─ test_predictions.png")

print("\n📝 Technical Report Notes:")
print("—" * 80)
print("1. Manual Labeling Methodology:")
print("   - Stratified sampling: 50 images per class (balanced)")
print("   - Manual verification untuk memastikan akurasi label")
print("   - Total: 750 labeled images")

print("\n2. Model Architecture:")
print(f"   - Base model: {config.MODEL_NAME} (pretrained on ImageNet)")
print(f"   - Transfer learning: Fine-tune all layers")
print(f"   - Optimizer: {config.OPTIMIZER.upper()}")
print(f"   - Learning rate: {config.LEARNING_RATE}")

print("\n3. Training Strategy:")
if config.USE_AUGMENTATION:
    print(f"   - Data augmentation: {config.AUGMENTATION_LEVEL} level")
    print("   - Techniques: Horizontal flip, rotation, color jitter")
else:
    print("   - No augmentation (natural data)")
print(f"   - Train-val split: 80-20 (stratified)")
print(f"   - Early stopping patience: {early_stop_patience}")

print("\n4. Performance Analysis:")
gap = history['train_acc'][-1] - best_val_acc
if gap < 5:
    print("   ✓ Good generalization (minimal overfitting)")
elif gap < 10:
    print("   ⚠ Slight overfitting detected")
else:
    print("   ❌ Significant overfitting - consider:")
    print("     - Reduce augmentation")
    print("     - Increase weight decay")
    print("     - Early stopping")

if best_val_acc >= 80:
    print(f"   ✓ Excellent validation accuracy: {best_val_acc:.2f}%")
elif best_val_acc >= 75:
    print(f"   ✓ Good validation accuracy: {best_val_acc:.2f}%")
else:
    print(f"   ⚠ Room for improvement. Consider:")
    print("     - Try different model architecture")
    print("     - Add more labeled data")
    print("     - Adjust hyperparameters")

print("\n5. Next Steps:")
print("   - Submit submission.csv to Kaggle")
print("   - Analyze confusion matrix for error patterns")
print("   - If score is low, try hybrid approach with clustering")

print("\n" + "="*80)
print("Good luck! 🚀")
print("="*80)